### ISSUE TITLE
Release on Node12

### ISSUE THREAD

**Issue by ISNIT0** [charto/nbind#133]
MWOffliner would love to have a node 12 release (https://github.com/openzim/mwoffliner/issues/707)

This merged pr: https://github.com/charto/nbind/pull/130 gets node 12 support working, but I think we still need to update the emscripten code.

**Comment by kelson42** [comment]
@jjrv Any timeline here? It is slowly becoming a problem to not support nodejs12 for software relying on nbind.

**Comment by mceIdo** [comment]
If anyone is interested, we've published a fork:
`@mcesystems/nbind`
(https://www.npmjs.com/package/@mcesystems/nbind)

We needed it for node 12 migration, so we just forked the module as is (plus a minor TS fix) and changed the name - works great.
@jjrv if you ever release here, please notify on this issue so we can deprecate our published module and revert to this one.

The fork: https://github.com/mceSystems/nbind

**Comment by kelson42** [comment]
@mceIdo Thank you very much

**Comment by kelson42** [comment]
@jjrv Also, if you have abandoned the maintenance of this repo. this would be really benefit to have a notice.

**Comment by nilres** [comment]
@jjrv I would also be very interested if there is any maintenance/development ongoing.

**Comment by kelson42** [comment]
@mceldo We still don't have checked with your fork
@nilres @mceldo I guess the project is abandonned. What would be a maintained alternative to nbind?

**Comment by mceIdo** [comment]
@kelson42, to be honest, given the awesome work done on N-API and the complementary node-addon-api for c++, next time I'll develop a new native module, or have a major refractor in one of my existing ones - I'll probably move to N-API based implementation

**Comment by nilres** [comment]
I was forced to go with embind directly. And work around the deficiencies it has.
What nbind was offering was a great addition but as it seems to be an abondon project I rather go with something that is activly maintained.

**Comment by Skywalker13** [comment]
> If anyone is interested, we've published a fork:
> `@mcesystems/nbind`
> (https://www.npmjs.com/package/@mcesystems/nbind)
> 
> We needed it for node 12 migration, so we just forked the module as is (plus a minor TS fix) and changed the name - works great.
> @jjrv if you ever release here, please notify on this issue so we can deprecate our published module and revert to this one.
> 
> The fork: https://github.com/mceSystems/nbind

It's broken with node >= v13 or electron >= 8 which use (node v12 but) a newer version of v8 (like node v13)
